const assert=require('node:assert/strict');
const ts=require('typescript');
const {createInputInventory}=require('../src/reasoning/functionInputs');
function inspect(text,name){
    const ast=ts.createSourceFile('fixture.js',text,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);
    let target;function visit(n){if(ts.isFunctionLike(n)&&n.name?.getText(ast)===name)target=n;ts.forEachChild(n,visit);}visit(ast);
    return createInputInventory(ast,n=>({start:n.getStart(ast),end:n.end}))(target);
}
const result=inspect('const config={}; function outer(clock){let count=0; function work(input){const local=input; count++; config.last=clock(); return {local,count,at:Date.now()};} return work;}','work');
const refs=result.references;
assert.equal(refs.find(r=>r.name==='input').ownership,'parameter');
assert.equal(refs.find(r=>r.name==='local').ownership,'local');
assert.equal(refs.find(r=>r.name==='count').ownership,'closure');
assert.equal(refs.find(r=>r.name==='count').access,'read_write');
assert.equal(refs.find(r=>r.name==='config').ownership,'module');
assert.equal(refs.find(r=>r.name==='clock').ownership,'closure');
assert.equal(refs.find(r=>r.name==='Date').ownership,'unresolved');
assert(!refs.some(r=>['last','now','at'].includes(r.name)));
const shadow=inspect('const state=1; function work(state){ {let state=3; consume(state);} return state; }','work');
assert.deepEqual(shadow.references.filter(r=>r.name==='state').map(r=>r.ownership),['local','parameter']);
const hoisted=inspect('let state=2; function work(){return state; var state;}','work');
assert.equal(hoisted.references[0].ownership,'local');
const catchScope=inspect('const error=1; function work(){try{fail();}catch(error){use(error);}return error;}','work');
assert.deepEqual(catchScope.references.filter(r=>r.name==='error').map(r=>r.ownership),['local','module']);
const nested=inspect('const hidden=1; function work(){ function other(){return hidden;} return 0; }','work');
assert(!nested.references.some(r=>r.name==='hidden'));
const defaults=inspect('const fallback=1; function work({value: local}=fallback){ return local; }','work');
assert.equal(defaults.references.find(r=>r.name==='fallback').ownership,'module');
assert.equal(defaults.references.find(r=>r.name==='local').ownership,'parameter');
const imported=inspect('const {normalize}=require("./dependency"); function work(text){return normalize(text);}','work');
assert.equal(imported.references.find(r=>r.name==='normalize').ownership,'module');
const dynamic=inspect('let state=1; function work(){eval("anything");return state;}','work');
assert.equal(dynamic.status,'unresolved_dynamic_scope');
assert(dynamic.references.every(r=>r.ownership==='unresolved'));
const {reportInputs}=require('../src/reasoning/functionInputReport');
const report=reportInputs({inputs:result});
assert.match(report,/count: surrounding function; read_write, read/);
assert.match(report,/config: module binding/);
assert.match(report,/Date: unresolved binding/);
assert.doesNotMatch(report,/local: local/);
assert.equal(reportInputs(null),'');
console.log('Lexical inputs: closures, module bindings, shadowing, hoisting, catch scopes, defaults and dynamic exclusions passed.');
