// Independent executable truth checks for subtle audit fixtures. These run
// only fixed test code, never code generated by a model.
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
async function main() {
    function buggySum(xs) { let n=0; for(let i=0;i<=xs.length;i++) n+=xs[i]; return n; }
    assert(Number.isNaN(buggySum([1,2,3])));
    assert(Number.isNaN(buggySum([])));
    function guarded(x) { if(x == null) return 'unknown'; return x.name; }
    assert.equal(guarded(null),'unknown');
    assert.equal(guarded(undefined),'unknown');
    async function returnWithoutAwait() { try { return Promise.reject(new Error('fixture')); } catch { return null; } }
    await assert.rejects(returnWithoutAwait(),/fixture/);
    const now=50000, savedAt=49000, ttlSeconds=30;
    assert.equal(now-savedAt<ttlSeconds,false);
    assert.equal(now-savedAt<ttlSeconds*1000,true);
    const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
    const content='x'.repeat(4000);
    assert.notEqual(hash(content.slice(0,3000)),hash(content));
    assert('/srv/application/secrets'.startsWith('/srv/app'));
    console.log('Independent audit oracles passed: NaN, null guard, async rejection, time units, hashes and sibling prefix.');
}
main().catch(error=>{console.error(error);process.exitCode=1;});
