const assert=require('node:assert/strict');
const {buildBundle}=require('../src/reasoning/sourceBundle');
const {scopeBundle}=require('../src/reasoning/symbolScope');
const {quotedInputs}=require('../src/reasoning/questionInputs');
const {derivePrimitiveFacts}=require('../src/reasoning/primitiveSemantics');
async function derive(body,value,extra='',argumentsMap={},parameters='text'){
    const text=`${extra}\nfunction f(${parameters}){${body}}`;
    const source={path:'src/semantic.js',version:'a'.repeat(64),complete:true,text:text.split('\n').map((l,i)=>`${i+1}: ${l}`).join('\n')};
    const bundle=scopeBundle((await buildBundle(source,{maxChars:30000})).bundle,'f');
    bundle.request.quotedInputs=quotedInputs('Input '+JSON.stringify(value));
    return derivePrimitiveFacts(bundle,[{inputId:'input0',parameter:'text',arguments:argumentsMap}]);
}
async function main(){
    const results=async(body,value)=> (await derive(body,value)).facts.map(f=>f.result);
    assert((await results(String.raw`return text.trim().split(/\s+/).length;`,'')).some(r=>r.value==='1'));
    assert((await results(String.raw`return text.replace(/\s/g, "").length;`,' a\tb ')).some(r=>r.value==='2'));
    assert((await results('return text.length;','😀')).some(r=>r.value==='2'));
    assert((await results('return parseFloat(text);','12cats')).some(r=>r.value==='12'));
    assert((await results('return parseFloat(text);','cats12')).some(r=>r.value==='NaN'));
    assert((await results('return Number(text);','12cats')).some(r=>r.value==='NaN'));
    assert((await results('return parseFloat(text);','-0')).some(r=>r.value==='-0'));
    assert((await results('return Number(text);','')).some(r=>r.value==='0'));
    assert((await results('return parseFloat(text);','Infinity')).some(r=>r.value==='Infinity'));
    const conditionalReturns=await results('return text.length;','abc');
    assert(conditionalReturns.every(r=>r.type==='number'&&r.value==='3'));
    assert.equal((await derive('return text.custom().length;','abc')).facts.length,0);
    const propagated=await derive('const clean=text.trim(); const size=clean.length; return size;',' ab ');
    assert(propagated.facts.some(f=>f.expressionText==='size'&&f.result.value==='2'&&f.relatedIds.length===3));
    const conditionalLocal=await derive('const clean=text.trim(); if(unknown){return clean.length;}',' ab ');
    assert(!conditionalLocal.facts.some(f=>f.expressionText==='clean.length'));
    const mutatedLocal=await derive(String.raw`const parts=text.split(/\s+/); parts.pop(); return parts.length;`,'a b');
    assert(!mutatedLocal.facts.some(f=>f.expressionText==='parts.length'));
    assert.equal((await derive('text="changed";return text.length;','abc')).facts.length,0);
    assert.equal((await derive('return custom(text);','abc')).facts.length,0);
    assert.equal((await derive('return text.replace(/a+/g,"x");','aaa')).facts.length,0);
    assert.equal((await derive('return parseFloat(text);','12cats','const parseFloat=other;')).facts.length,0);
    assert.equal((await derive('return parseFloat(text);','12cats','parseFloat=other;')).facts.length,0);
    assert.equal((await derive('return text.trim();',' abc ','String.prototype.trim=other;')).facts.length,0);
    assert.equal((await derive('eval(code);return text.length;','abc')).facts.length,0);
    assert.equal((await derive('return Number(text);','2','import * as Number from "./other.js";')).facts.length,0);
    const conditional=await derive('if (unknown) return text.length;','ab');
    assert(conditional.facts.every(f=>f.assumptions.includes('Not proof of reachability')));
    const guardBody='try { const v=parseFloat(text); const t=parseFloat(total); if(isNaN(v)||isNaN(t)||t===0) return "invalid"; } catch(error) {}';
    const guard=async(value,args)=> (await derive(guardBody,value,'',args,'text,total')).facts.find(f=>f.expressionText==='isNaN(v)||isNaN(t)||t===0');
    assert.deepEqual((await guard('7kg',{total:14})).result,{type:'boolean',value:false});
    assert.deepEqual((await guard('kg7',{total:14})).result,{type:'boolean',value:true});
    assert.deepEqual((await guard('7kg',{total:0})).result,{type:'boolean',value:true});
    assert.equal(await guard('7kg',{}),undefined);
    const supported=await guard('7kg',{total:14});
    assert.equal(supported.relatedIds.length,3);
    assert.deepEqual(supported.arguments,{total:14});
    await assert.rejects(guard('7kg',{other:14}),/Invalid semantic scenario argument/);
    await assert.rejects(guard('7kg',{text:14}),/Invalid semantic scenario argument/);
    await assert.rejects(guard('7kg',{total:{value:14}}),/Invalid semantic scenario argument/);
    await assert.rejects(guard('7kg',{total:Infinity}),/Invalid semantic scenario argument/);
    assert(!(await derive(guardBody,'7kg','const isNaN=other;',{total:14},'text,total')).facts.some(f=>f.expressionText.startsWith('isNaN(')));
    assert.equal((await derive('total=0; if(total===0) return text;','7kg','',{total:14},'text,total')).facts.length,0);
    assert(!(await derive('const v=parseFloat(text); unknown(); if(v===7) return text;','7kg')).facts.some(f=>f.expressionText==='v===7'));
    assert((await results('return true || unknown();','x')).some(r=>r.type==='boolean'&&r.value===true));
    assert(!(await results('return unknown() || true;','x')).length);
    assert((await results('return !false && text !== "";','x')).some(r=>r.type==='boolean'&&r.value===true));
    const service=require('../src/reasoning/projectQuestion').createService({repository:{get:async()=>null},evidenceBundle:true});
    const command={filename:'src/tools/utilities/characterCount.js',question:'Inspect " a "',targetSymbol:'characterCount',inputBindings:[{inputId:'input0',parameter:'text'}]};
    const result=await service.answer(command,{agentId:'alice',complete:async(m,o)=>{
        assert.match(m[1].content,/bounded-primitive-expression-v3/);
        const id=o.format.properties.claims.items.properties.evidenceIds.items.enum.find(id=>id.startsWith('semantic'));
        assert(id);
        return JSON.stringify({claims:[{text:'An expression result is available.',evidenceIds:[id]}],predictions:[],expressionAssertions:[],unknowns:[]});
    }});
    assert(result.staticEvidence.some(f=>f.result.value==='3'));
    assert(result.staticEvidence.some(f=>f.result.value==='1'));
    assert.match(result.reply,/Atlas-derived expression results/);
    assert.doesNotMatch(result.speech,/Atlas-derived expression results/);
    await assert.rejects(service.answer({...command,inputBindings:[{inputId:'input0',parameter:'other'}]},{agentId:'alice',complete:()=>{throw new Error('Should not generate');}}),/Invalid semantic input binding/);
    console.log('Bounded primitive semantics, exact results, unsupported and shadowing exclusions passed.');
}
main().catch(e=>{console.error(e);process.exitCode=1;});
