const assert=require('node:assert/strict');
const {readRange}=require('../src/core/sourceReader');
const checks=require('../src/reasoning/profileEvidence');
const {createService}=require('../src/memory/projectUnderstanding');
async function main(){
    const source=readRange('src/agents/agentProfiles.js',1,200);
    await assert.rejects(checks.collect(source),/Explicit/);
    await assert.rejects(checks.collect(source,{authorized:true,permission:{allowed:false}}),/not permitted/);
    await assert.rejects(checks.collect({...source,path:'src/unknown.js'},{authorized:true}),/No approved/);
    await assert.rejects(checks.collect({...source,version:'0'.repeat(64)},{authorized:true}),/changed/);
    const evidence=await checks.collect(source,{authorized:true});
    assert.equal(evidence.results.length,5);
    assert.deepEqual(evidence.results.find(r=>r.id==='fresh-cache').observed,{source:'database',degraded:false,revision:7,calls:0});
    assert(checks.current(evidence,source));
    const secondSource=readRange('src/core/codeEvidence.js',1,200);
    const second=await checks.collect(secondSource,{authorized:true});
    assert.equal(second.results.length,7);
    assert(checks.current(second,secondSource));
    assert(!checks.current({...second,path:source.path},secondSource),'Evidence cannot cross files');
    assert(!checks.current(evidence,secondSource));
    assert.equal(second.results[0].observed.coverage,null);
    assert.equal(second.results.find(r=>r.id==='expiry-boundary').observed.at600000ReturnsOriginal,true);
    assert.equal(second.results.find(r=>r.id==='whole-line-truncation').observed.containsPartialLine,false);
    await assert.rejects(checks.collect(secondSource,{authorized:true,launchCheck:async()=>evidence.results}),/Incomplete/);
    assert(!checks.current({...evidence,dependencies:{}},source));
    await assert.rejects(checks.collect(source,{authorized:true,launchCheck:async()=>[]}),/Incomplete/);
    const validReply=()=>JSON.stringify({cases:evidence.results.map(r=>({id:r.id,observed:r.observed,explanation:'Source-backed explanation for this fixed scenario.'}))});
    assert.equal((await checks.explain(source,evidence,{complete:async()=>validReply()})).status,'unverified');
    const contradicted=JSON.parse(validReply());contradicted.cases[2].observed.calls=5;
    assert.equal((await checks.explain(source,evidence,{complete:async()=>JSON.stringify(contradicted)})).status,'withheld');
    assert.equal((await checks.explain(source,evidence,{complete:async()=>{throw new Error('offline');}})).status,'withheld');
    assert.equal((await checks.explain(source,evidence,{timeoutMs:5,complete:()=>new Promise(()=>{})})).status,'withheld');
    let record={schema:2,project:'atlas',agentId:'alice',path:source.path,version:source.version,analysis:{}};
    const repository={get:async()=>record,put:async(_key,value)=>{record=value;}};
    const service=createService({repository});
    const command={action:'check',filename:source.path};
    const options={agentId:'alice',complete:async()=>{throw new Error('offline');}};
    const result=await service.handle(command,options);
    assert.match(result,/Saved checked evidence/);
    assert.match(result,/five fixed checks passed/);
    assert.equal(record.checkedEvidence.commentary.status,'withheld');
    const failed=createService({repository:{get:async()=>record,put:async()=>{throw new Error('disk full');}}});
    assert.match(await failed.handle(command,options),/NOT saved/);
    await assert.rejects(service.handle(command,{...options,isCancelled:()=>true}),/cancelled/);
    console.log('Checked evidence: real isolated outcomes, permissions, provenance, withheld contradictions, model failure and persistence passed.');
}
main().catch(error=>{console.error(error);process.exitCode=1;});
