const assert=require('node:assert/strict');
const {createService,detect}=require('../src/reasoning/projectQuestion');
async function main(){
    const source={path:'src/example.js',version:'a'.repeat(64),complete:true,text:'1: function answer() { return 42; }'};
    let record=null,messages;
    const service=createService({read:async()=>source,repository:{get:async()=>record,put:()=>{throw new Error('Must not write');}}});
    const command={filename:source.path,question:'What does src/example.js return?'};
    const options={agentId:'alice',complete:async m=>{messages=m;return JSON.stringify({claims:[{text:'It returns 42.',lines:[1]}],unknowns:[]});}};
    const first=await service.answer(command,options);
    assert.match(first.reply,/No saved knowledge/);
    assert.match(first.speech,/It returns 42/);
    assert.doesNotMatch(first.speech,/src\/|Source:|No saved knowledge/);
    const tree=['src/utils/keywordExtractor.js','src/response/recovery.js','src/other/recovery.js'];
    const spoken=q=>detect(q,null,'alice',0,tree);
    assert.equal(spoken('How does the keyword extractor work?').filename,tree[0]);
    assert.equal(spoken('Explain keywordExtractor.js').filename,tree[0]);
    assert.equal(spoken('How does the recovery file work?').choices.length,2);
    assert.equal(spoken('Explain the response recovery file').filename,tree[1]);
    assert.equal(spoken('How does recovery feel?'),null);
    assert.equal(spoken('Can you delete the keyword extractor file?'),null);
    record={project:'atlas',agentId:'alice',path:source.path,version:source.version,analysis:{observations:[{text:'Unverified hint'}]}};
    await service.answer(command,options);assert.match(messages[1].content,/Unverified hint/);
    record.version='b'.repeat(64);assert.match((await service.answer(command,options)).reply,/Stale stored/);assert.doesNotMatch(messages[1].content,/Unverified hint/);
    record.agentId='bob';await assert.rejects(service.answer(command,options),/ownership/);
    record=null;
    await assert.rejects(service.answer(command,{...options,complete:async()=>JSON.stringify({claims:[{text:'wrong citation',lines:[999]}],unknowns:[]})}),/citations/);
    const timed=createService({repository:{get:async()=>null},read:async()=>source,timeoutMs:5});
    await assert.rejects(timed.answer(command,{...options,complete:()=>new Promise(()=>{})}),/timed out/);
    const unavailable=createService({repository:{get:async()=>{throw new Error('offline');}},read:async()=>source});
    assert.match((await unavailable.answer(command,options)).reply,/Stored knowledge unavailable/);
    let reads=0;
    const changed=createService({repository:{get:async()=>null},read:async()=>({...source,version:++reads===1?source.version:'c'.repeat(64)})});
    await assert.rejects(changed.answer(command,options),/Source changed/);
    assert(detect(command.question));
    assert.equal(detect('Can you delete src/example.js?'),null);
    assert.equal(detect('Do not read src/example.js'),null);
    const prior={path:source.path,agentId:'alice',at:100};
    assert(detect('What does that file do?',prior,'alice',200));
    assert.equal(detect('What does that file do?',prior,'bob',200),null);
    assert.equal(detect('What does that file do?',prior,'alice',600100),null);
    const actual=require('../src/core/sourceReader').readRange('src/core/codeEvidence.js',1,200);
    const checked=await require('../src/reasoning/profileEvidence').collect(actual,{authorized:true});
    const checkedRecord={project:'atlas',agentId:'alice',path:actual.path,version:actual.version,analysis:{observations:[]},checkedEvidence:checked};
    const checkedService=createService({repository:{get:async()=>checkedRecord}});
    const checkedAnswer=await checkedService.answer({filename:actual.path,question:'How does capture work?'},options);
    assert.equal(checkedAnswer.packet.checkedObservations.length,7);
    checkedRecord.checkedEvidence.dependencies={};
    const staleChecks=await checkedService.answer({filename:actual.path,question:'How does capture work?'},options);
    assert.equal(staleChecks.packet.checkedObservations.length,0);
    assert.match(staleChecks.reply,/Stale checked evidence excluded/);
    console.log('Project question retrieval, stale/ownership boundaries, failure paths and no-write behavior passed.');
}
main().catch(error=>{console.error(error);process.exitCode=1;});
